[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snap-conv"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = []

[tool.hatch.version]
path = "snap_conv/__init__.py"
